spring:
  application:
    name: maismaes

  datasource:
    url: jdbc:mysql://localhost:3306/maismaes_db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://chatuser:chatpass@localhost:27017/chatdb?authSource=admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

security:
  secret: maismaes

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:seu-email@gmail.com}
  password: ${MAIL_PASSWORD:sua-senha-de-app}
  from: ${MAIL_FROM:nao-responda@maismaes.com.br}

spring.mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:seu-email@gmail.com}
  password: ${MAIL_PASSWORD:sua-senha-de-app}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

recuperacao-senha:
  expiracao-minutos: 10

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    com.maismaes.com.br.controller.ChatController: DEBUG
    com.maismaes.com.br.config.WebSocketEventListener: DEBUG

